version: "3.6"

services:

  mysql:
    platform: linux/x86_64
    image: mysql:8
    cap_add:
      - SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
      - db_log:/var/log/mysql
    restart: always
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306


volumes:
  db_data:
    driver: local
  db_log:
    driver: local
